server {
    listen 8082;
    server_name localhost;

    port_in_redirect off;

    # 1. AQUÍ SERVIMOS TU PÁGINA WEB
    location /vm2/front/ {
        # Usamos root en lugar de alias (Nginx buscará automáticamente en /usr/share/nginx/html/vm2/front/)
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /vm2/front/index.html;
    }

    # 2. EL PROXY AL BACKEND (Este se queda igual, estaba perfecto)
    location /vm2/ {
        proxy_pass http://172.17.0.1:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
